# Generated by Django 2.1.1 on 2018-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_url',
            field=models.CharField(default='<i class="fas fa-sticky-note"></i>', max_length=50),
        ),
    ]
