# Generated by Django 2.1.1 on 2018-10-21 13:14

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181021_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
